spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: ${SPRING_PROFILE}
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
server:
  shutdown: graceful
